### PR TITLE
[#234] Validate uris

### PR DESCRIPTION
**Pull request by kindly**
Add dependancy to let jsonschema validate uris

### CODE REVIEW

**Comment by Bjwebb** [comment]
Happy to see this merged. Might be good to have a test that this works though.

**Comment by Bjwebb** [comment]
Discussed this on today's call. We're also not sure what the implications of enabling this might be, so may be best not to merge it for now. As a result, it might be useful for me to deploy this branch as a test instance of Cove?

**Comment by Bjwebb** [comment]
Test instance of Cove for this pull request http://234-validate-uri.dev.cove.opendataservices.coop/

@kindly Can you remember if you had any specific concerns about enabling this?

**Comment by caprenter** [comment]
I've spent some time messing with a json file to put a single broken URI into it, and it does pick up the problem.

This definitely needs a test writing for it. I'm not sure how you would want to do that. 
JSON that fails only on the URI is added here. (derived from existing fixture data)

```json
{
    "grants": [
        {
            "currency": "GBP", 
            "grantProgramme": [
                {
                    "code": "AAC", 
                    "title": "Arts Awards Funding Committee"
                }
            ], 
            "id": "360G-ertdghrust-10763865et",
            "description": "A big grant",
            "title": "Silent Sigh", 
            "url": "ers/Managing-a-grant/Grants-awarded/index.htm", 
            "fundingOrganization": [
                {
                    "id": "GB-CHC-2xxxx", 
                    "name": "The Trust"
                }
            ], 
            "dateModified": "2015-03-14", 
            "plannedDates": [
                {
                    "duration": "30"
                }
            ], 
            "amountAwarded": 152505, 
            "recipientOrganization": [
                {
                    "addressLocality": "London", 
                    "name": "A Project Limited",
                    "id":"wibble"
                }
            ], 
            "Grant type": "Large Arts Awards", 
            "awardDate": "2014-03-20T12:00:00Z"
        }
       
    ]
}
```

**Pull request merged**
