### PR TITLE
360 - More info content always visible 

### PR DESCRIPTION
**Pull request by edugomez**
#674

### CODE REVIEW

**Comment by robredpath** [comment]
Hmmm. I like the idea of putting this info in front of people more readily, because I'm sure it's not read much. But, having this open by default makes it a bit of a wall of text on the front page. 

Could we have the answers hidden by default and revealed on click?

**Comment by edugomez** [comment]
> Could we have the answers hidden by default and revealed on click?
Yes

**Comment by edugomez** [comment]
360-faq

**Comment by robredpath** [comment]
Looks great, @edugomez ! Can we remove the top horizontal line above the first question though?

**Comment by edugomez** [comment]
> Can we remove the top horizontal line..?

Yes

**Comment by edugomez** [comment]
@robredpath The top ```<hr>``` has been removed.

**Comment by robredpath** [comment]
Great! @KDuerden are you ok if we merge this in for 360 CoVE?  It keeps the More Info box open all the time (as requested in #674 ) but just the section titles - the text is hidden to avoid it being too much of a wall of text.

**Comment by KDuerden** [comment]
Yes, that all looks good, happy for you to merge to 360 CoVE.

**Pull request merged**
