### PR TITLE
Update Privacy Policy with necessary info for GDPR

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by Bjwebb** [comment]
@KDuerden Here's a dev deploy for the 360Giving terms http://gdpr-privacy-notice.cove-360-dev.default.threesixtygiving.uk0.bigv.io/terms/

**Comment by Bjwebb** [comment]
@jpmckinney Here's a dev deploy for new OCDS Validator terms http://gdpr-privacy-notice.dev.cove.opendataservices.coop/validator/terms/

What's changed:
* "Privacy Policy" section has changed entirely
* OCP is more consistently identified as the owner of the website
* Under "Data uploaded to this website" we now say "Please do not submit any non-public personal data to this application."

**Comment by jpmckinney** [comment]
Looks good. The Privacy Policy seems to be largely description of what we collect and why, and reminding people of their rights (rather than e.g. establishing new rights, privileges or processes).

**Comment by KDuerden** [comment]
Hi @Bjwebb - would you be willing to change the sub-section to Privacy notice, rather than Privacy policy? This would make it more inline with our other websites.

**Comment by Bjwebb** [comment]
@KDuerden Sure, will do that.

**Comment by Bjwebb** [comment]
@jpmckinney Yes, I think that's an accurate assessment.

Due to time constraints, we plan to make this live with the English only (ie. on the Spanish site, you'll see the new English text). Subsequently, we need to make a decision whether a legal document like this should be translated (the one on the main OCP website isn't).

**Pull request merged**
