### PR TITLE
Fix show/shown typo

### PR DESCRIPTION
**Pull request by andylolz**

### CODE REVIEW

**Comment by caprenter** [comment]
While this is only a typo...

We do have a policy of getting contributor agreements signed before we accept contributions. It's hopefully not too arduous, and protects the software in the long term to be sure that all contributions can be re-licensed (under an open licence) if needed.

Details are here: https://github.com/OpenDataServices/cove/blob/master/CONTRIBUTING.md

@andylolz - would you be happy to sign an agreement so we can accept this change?

**Comment by andylolz** [comment]
No problem. Signed

**Comment by caprenter** [comment]
Thanks @andylolz that's great. I'll get a signed copy back to you asap.

**Comment by andylolz** [comment]
> I'll get a signed copy back to you asap.

@caprenter Did you? I don’t think so. I don’t see it in my emails, at any rate.

**Comment by robredpath** [comment]
@andylolz - @caprenter has left the organisation, but I can see from our CRM that a copy of your CLA was sent to the email address used on 2017-02-28 at 12:08. I can re-send it, if you'd like?

**Comment by andylolz** [comment]
Aha! You’re right – apologies. I see it now. Thanks!

**Pull request merged**
