### PR TITLE
Refactor templates

### PR DESCRIPTION
**Pull request by robredpath**

### CODE REVIEW

**Comment by robredpath** [comment]
This PR should result in no change to the output. I've run a validation with all three CoVEs and eyeballed the output in each case, and I think we're good. Additional eyes welcome.

**Comment by robredpath** [comment]
Fixed @Bjwebb

**Comment by Bjwebb** [comment]
More info box appear on the terms and conditions page, and the 360Giving common errors page, where it didn't before.

**Comment by robredpath** [comment]
@Bjwebb @edugomez could you take a look at this? I've checked over the output but additional eyes are always useful. 

The 'how to use' box disappears from IATI CoVE, but that's intentional - until we get some content to actually put in it (which is the job that started all of this off!)

**Pull request merged**
