### PR TITLE
Change terminology for validation in OCDS

### PR DESCRIPTION
**Pull request by jpmckinney**
Pursuant to 2944 in CRM.

### CODE REVIEW

**Comment by jpmckinney** [comment]
PO files need to be updated (I haven't found instructions, and running `python manage.py makemessages -l es` produces a lot of whitespace differences).

I don't have access to `secret_data_test`, which also causes a failure.

**Comment by jpmckinney** [comment]
This should be part of the Apr-May 2019 sprint.

**Comment by jpmckinney** [comment]
@robredpath Please have this merged early in the sprint – to avoid a conflict.

**Comment by robredpath** [comment]
@kindly will get these changes in at the start of the sprint. This is likely to be through pulling the changes in to a branch owned by an organisational user so that we can sort out the pulling forward of the branch cleanly.

**Comment by robredpath** [comment]
@odscjames will take this on, as this doesn't seem to have happened yet.

**Comment by odscjames** [comment]
This will hopefully be dealt with in https://github.com/OpenDataServices/cove/pull/1164

**Comment by odscjames** [comment]
#1164 has been merged

**Pull request closed without merging**
