### PR TITLE
Validate against IATI org schema

### LINKED ISSUE #922: schema_aiti typo
Should be schema_iati

### PR DESCRIPTION
**Pull request by andylolz**
Make a start at #959.

Also happens to fix #922.

### CODE REVIEW

**Comment by Bjwebb** [comment]
Thanks for taking a look at this.

Am I right in thinking this validates against the org schema first, and if that fails tries the activity schema instead? I suspect this would be somewhat confusing behaviour.

**Comment by andylolz** [comment]
> Am I right in thinking this validates against the org schema first, and if that fails tries the activity schema instead? I suspect this would be somewhat confusing behaviour.

That’s correct, yes. This PR isn’t a solution – as described, it just makes a start at tackling the problem.

So you’ll see a failure against the activity schema if you try to test an invalid org file. I agree that this would be confusing (though note that this is what happens currently anyway.)

I guess the correct approach would be to peek at the data and attempt to identify which schema to use?

**Comment by andylolz** [comment]
> peek at the data and attempt to identify which schema to use

I did it this way, and added a test. @Bjwebb does this look okay?

**Comment by andylolz** [comment]
This issue is also dependent on OpenDataServices/flatten-tool#150.

**Comment by andylolz** [comment]
Cool – a load of stuff that was blocking this has now been cleared!

I have a nagging feeling that I wanted to get the meta tab roundtripping before finishing this one off, but I don’t exactly remember why…

**Comment by Bjwebb** [comment]
Before this Pull Request can be merged, I think the remaining tasks are:
- [ ] Create a new tagged version of flatten-tool
- [ ] Update the requirements files in this pull request
- [ ] Someone who's not me to review the code

**Comment by andylolz** [comment]
:clap::clap::clap:

**Pull request merged**
