### PR TITLE
[#347] Add xdist to dev reqs for parallel testing

### PR DESCRIPTION
**Pull request by robredpath**

### CODE REVIEW

**Comment by caprenter** [comment]
This will probably/may pass if you grab the fix in:
https://github.com/OpenDataServices/cove/commit/f331476c6f3dfb016822b0b471208ff78cbd3e38

**Comment by Bjwebb** [comment]
Looks like this has been rebased, and then merged with the non-rebased copy. Might be best to undo that merge?

**Comment by robredpath** [comment]
@Bjwebb I've squashed anyway, which I think solves the problem

**Comment by Bjwebb** [comment]
@kindly I've made some changes here to ensure that the requirements for this are in the pinned file. I think it would be good for you to review and merge, or for us to discuss tomorrow morning.

**Comment by Bjwebb** [comment]
This is failing intermittently on Travis and on my local machine. @robredpath Could you take a look at this?

**Comment by Bjwebb** [comment]
I think I've realised what's wrong here, no all our tests load the page they're intending to test, instead relying on the page that was loaded by the previous test. This causes inconsistent failures with xdist, because which set of tests a particular browser will be scheduled will vary. Fix is to make sure our tests load the pages they need. I'll take a look at that.

**Comment by Bjwebb** [comment]
Looks like it works. \o/

**Pull request merged**
