### PR TITLE
Remove libcoveocds

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by odscjames** [comment]
This follows on from and includes #1256 and should not be looked at until that is merged, at which point this can be rebased (maybe rerun process if it's been a while) and sorted

**Comment by odscjames** [comment]
[Refactor OCDS-specific code into a new application](https://trello.com/c/6SyOfmT6/49-refactor-ocds-specific-code-into-a-new-application)

**Comment by odscjames** [comment]
This is failing with

> No matching distribution found for zipp==3.0.0

Zipp 3 was released on Feb 17th, yesterday. Is this just a Travis caching issue? 

Let's try rerunning ./update_requirements.sh  and rerunning on Travis in a few days

**Comment by odscjames** [comment]
Fixed by making sure I ran it in a Python3.5 venv

**Comment by odscjames** [comment]
We should probably deploy IATI and 360 after merging this.

**Review by Bjwebb — APPROVED** [review]

**Pull request merged**
