### PR TITLE
Creates a more designed landing page

### PR DESCRIPTION
**Pull request by caprenter**
For discussion

Adds a couple of 'landing' boxes for each standard and a few other bits

### CODE REVIEW

**Comment by Bjwebb** [comment]
Have rebased onto current master.

@caprenter Should there be logo images included in the repository? If so, I think you missed them from your commit.

Otherwise, looks good to me.

**Comment by caprenter** [comment]
Yep - logos should be in there. Will add them.

**Comment by Bjwebb** [comment]
This is now up on http://minor-live-improvements.dev.cove.opendataservices.coop/ for review.

As this is a change to the look of the site, @timgdavies might want to review before this gets merged.

**Comment by timgdavies** [comment]
I'm liking the look of this.

+1 from me.

On Tue, Aug 4, 2015 at 4:14 PM, Ben Webb <notifications@github.com> wrote:

> This is now up on
> http://minor-live-improvements.dev.cove.opendataservices.coop/ for review.
>
> As this is a change to the look of the site, @timgdavies
> <https://github.com/timgdavies> might want to review before this gets
> merged.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenDataServices/cove/pull/76#issuecomment-127645804>.
>



-- 


+44 (0)7834 856 303
@timdavies
http://www.timdavies.org.uk

**Pull request merged**
