### PR TITLE
End of September 2017 live deployment 

### PR DESCRIPTION
**Pull request by Bjwebb**
URL for testing:
* 360Giving - http://release-201709.cove-360-dev.default.threesixtygiving.uk0.bigv.io/
* OCDS - http://release-201709.dev.cove.opendataservices.coop/

Planned deployment date: Thursday 28th September

#### Summary of changes for this deployment

360Giving:
* Modify additional check for incomplete location data https://github.com/OpenDataServices/cove/issues/801
* Add a "See all" link to additional checks, which opens a modal list https://github.com/OpenDataServices/cove/pull/813
* Fix some bugs in flattening (JSON->Spreadsheet) with titles https://github.com/OpenDataServices/flatten-tool/pull/169
* Describe additional checks on hidden page https://github.com/OpenDataServices/cove/pull/840

OCDS:
* Handle jsonref exceptions https://github.com/OpenDataServices/cove/pull/826
* Error message for missing OCDS package format #831

Both:
* Better Spreadsheet conversion warnings for conflicting headers in different rows https://github.com/OpenDataServices/flatten-tool/pull/169
* Minor bug fixes https://github.com/OpenDataServices/cove/pull/837

#### Tasks in deploy process

Before merge:
- [x] Re-run translations if any text has changed
- [x] Create a new branch `release-201709` if it doesn't exist.
- [x] Deploy to a subdomain on `cove-dev` for OCDS http://release-201709.dev.cove.opendataservices.coop/
- [x] Check that the correct commit has been deployed using the link in the footer http://release-201709.dev.cove.opendataservices.coop/
- [x] Run `CUSTOM_SERVER_URL=http://release-201709.dev.cove.opendataservices.coop/ DJANGO_SETTINGS_MODULE=cove_ocds.settings py.test cove_ocds/tests_functional.py` - redo this for each redeploy to the subdomain
- [x] Deploy to a subdomain on the 360 dev server http://release-201709.cove-360-dev.default.threesixtygiving.uk0.bigv.io/
- [x] Check that the correct commit has been deployed using the link in the footer http://release-201709.cove-360-dev.default.threesixtygiving.uk0.bigv.io/ 
- [x] Run `CUSTOM_SERVER_URL=http://release-201709.cove-360-dev.default.threesixtygiving.uk0.bigv.io/  DJANGO_SETTINGS_MODULE=cove_360.settings py.test cove_360/tests_functional.py` - redo this for each redeploy to the subdomain

Steps above need redoing for additional commits.

After merge:
- [ ] Run salt highstate on `cove-360-live`
- [ ] Check that the correct commit has been deployed using the link in the footer http://dataquality.threesixtygiving.org/
- [ ] Run `CUSTOM_SERVER_URL=https://dataquality.threesixtygiving.org/ DJANGO_SETTINGS_MODULE=cove_360.settings py.test cove_360/tests_functional.py` on a local copy of the updated live branch
- [ ] Run salt highstate on `cove-live-ocds`
- [ ] Check that the correct commit has been deployed using the link in the footer http://standard.open-contracting.org/validator/
- [ ] Run `CUSTOM_SERVER_URL=http://standard.open-contracting.org/ DJANGO_SETTINGS_MODULE=cove_ocds.settings py.test cove_ocds/tests_functional.py` on a local copy of the updated live branch
- [ ] Check that changes on live are merged back into master too

### CODE REVIEW

**Comment by Bjwebb** [comment]
@edugomez could you take a looks at the cove and cove_ocds resources on transifex https://www.transifex.com/OpenDataServices/cove/language/es/

**Comment by stevieflow** [comment]
@Bjwebb I cant see to see a link for testing the 360 deployment...

**Comment by Bjwebb** [comment]
d'oh - http://release-201709.cove-360-dev.default.threesixtygiving.uk0.bigv.io/

**Comment by timgdavies** [comment]
Tagging @jpmckinney just for awareness of upcoming updates to OCDS CoVE validator, planned for deployment next week.

**Comment by Bjwebb** [comment]
Now live on http://dataquality.threesixtygiving.org/ and http://standard.open-contracting.org/validator/

**Pull request merged**
