### PR TITLE
[#189] Add data tables for grants.

### PR DESCRIPTION
**Pull request by kindly**
The data tables plugin works out of the box and gracefully degrades with no js.

### CODE REVIEW

**Comment by Bjwebb** [comment]
When I try this with http://www.wolfson.org.uk/media/2740/wolfson-foundation-grants-2014.xlsx the table is blank until I click on page.

**Comment by Bjwebb** [comment]
Additionally, it would be good to add a basic tests that this loads correctly, and that the text we expect (ie one of the first 10 rows) is still shown.

**Comment by kindly** [comment]
The issue with that file is that it has ten empty grants in it.  Flattentool seems to be converting empty rows in a spreadsheed to empty grants '{}'. 
But, agreed there should be a test or two.

**Comment by Bjwebb** [comment]
Thanks for explaining. There's an issue for this in flattentool at https://github.com/OpenDataServices/flatten-tool/issues/80

**Pull request merged**
