### PR TITLE
Apply Django security update to requirements_dev also

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by Bjwebb** [comment]
Looks like this might be failing due to changes in the OCDS standard repo. @kindly do you know anything about this?

**Comment by edugomez** [comment]
@Bjwebb the problem is this 404 at https://raw.githubusercontent.com/open-contracting/standard/1.1-dev/standard/schema/codelists/releatedProcessScheme.csv,  an url buit in Cove in `cove.lib.common._load_codelists` to retrieve a codelist file, notice the typo in _re**lea**tedProcessScheme.csv_. `_load_codelists` gets a `requests` exception and completely swallows it silently (perhaps not ideal behaviour for debugging).

**Comment by Bjwebb** [comment]
Thanks @edugomez, the OCDS standard PR you made is merged now https://github.com/open-contracting/standard/pull/449.

Based on local testing, I think this will still fail, because we look for `procurementCategory`, but this is now called `mainProcurementCategory` - we just need to change that key.

**Comment by Bjwebb** [comment]
@edugomez if you approve and merge this pull request, you should be able to use it as the base for other branches, so that they don't fail.

**Comment by edugomez** [comment]
@Bjwebb that's cool, merging now

**Pull request merged**
