### PR TITLE
[#715] cove_ocds: Improve behaviour for version field including patch

### PR DESCRIPTION
**Pull request by edugomez**
See https://github.com/OpenDataServices/cove/issues/715#issuecomment-314447798

pr-715-error

_______________________________________________________________________________________

pr-715-explore

### CODE REVIEW

**Comment by timgdavies** [comment]
Reviewing based on the screenshots. 

I notice that where it says it is validating against 'current default version' it is 1.0 that is selected. Should this be 1.1?

For the first screenshot I'd suggest one minor tweak to the language to add:

("1.1.0" should appear as "1.1" in your data **as the validator always uses the latest patch release for a major.minor version**) 

Otherwise - this is looking great.

**Comment by edugomez** [comment]
I ended up adding more stuff to this branch and PR than originally planned. In particular, there are changes to the default version:
* The default version is now the latest version registered in _cove.settings.py_ (at time of writing this, '1.1')
* That is the version used if the data contains a `"version"` field but the version is not recognised.
* If there is no `"version"` field we assume and will use '1.0'

@timgdavies

**Comment by edugomez** [comment]
@Bjwebb @robredpath @timgdavies it would be nice to have this PR reviewed/approved/merged whenever you have a minute

**Comment by Bjwebb** [comment]
Supplying a number as the version now causes a 500 error.

```diff
diff --git a/cove_ocds/tests.py b/cove_ocds/tests.py
index 7ab4339..20acf9a 100644
--- a/cove_ocds/tests.py
+++ b/cove_ocds/tests.py
@@ -341,6 +341,10 @@ def test_get_schema_deprecated_paths():
     '{"version": "1.1", "records" : true}',
     '{"version": "1.1", "records" : "test"}',
     '{"version": "1.1", "records" : {"version": "1.1", "a":"b"}}',
+    '{"version": 1.1, "releases": {}}',
+    '{"version": null, "releases": {}}',
+    '{"version": true, "releases": {}}',
+    '{"version": false, "releases": {}}',
 ])
 def test_explore_page(client, json_data):
     data = SuppliedData.objects.create()
```

**Comment by Bjwebb** [comment]
This is now deployed on the dev : http://dev.cove.opendataservices.coop/validator/

**Comment by edugomez** [comment]
@Bjwebb great, thanks!

**Pull request merged**
