### PR TITLE
End of January 2018 live deployment 

### PR DESCRIPTION
**Pull request by Bjwebb**
URL for testing:
* 360Giving - http://release-201801.cove-360-dev.default.threesixtygiving.uk0.bigv.io/
* OCDS - http://release-201801.dev.cove.opendataservices.coop/

Planned deployment date:  Monday 22nd January

#### Summary of changes for this deployment

OCDS:
* List the schema version from the file, and add a CSS tooltip for version switching https://github.com/OpenDataServices/cove/pull/924
* Don't 500 error on bad extension schemas https://github.com/OpenDataServices/cove/issues/929
* Cache the schema https://github.com/OpenDataServices/cove/pull/932

360Giving:
* Add sample data upload link https://github.com/OpenDataServices/cove/pull/941
* Text changes https://github.com/OpenDataServices/cove/issues/672 https://github.com/OpenDataServices/cove/issues/593 https://github.com/OpenDataServices/cove/pull/937 https://github.com/OpenDataServices/cove/issues/84

#### Tasks in deploy process

Before merge:
- [x] Re-run translations if any text has changed https://github.com/OpenDataServices/cove/issues/946
- [x] Create a new branch `release-201801` if it doesn't exist.
- [x] Deploy to a subdomain on `cove-dev` for OCDS http://release-201801.dev.cove.opendataservices.coop/
- [x] Check that the correct commit has been deployed using the link in the footer http://release-201801.dev.cove.opendataservices.coop/
- [x] Run `CUSTOM_SERVER_URL=http://release-201801.dev.cove.opendataservices.coop/ DJANGO_SETTINGS_MODULE=cove_ocds.settings py.test cove_ocds/tests_functional.py` - redo this for each redeploy to the subdomain
- [x] Deploy to a subdomain on the 360 dev server http://release-201801.cove-360-dev.default.threesixtygiving.uk0.bigv.io/
- [x] Check that the correct commit has been deployed using the link in the footer http://release-201801.cove-360-dev.default.threesixtygiving.uk0.bigv.io/ 
- [x] Run `CUSTOM_SERVER_URL=http://release-201801.cove-360-dev.default.threesixtygiving.uk0.bigv.io/  DJANGO_SETTINGS_MODULE=cove_360.settings py.test cove_360/tests_functional.py` - redo this for each redeploy to the subdomain

Steps above need redoing for additional commits.

After merge:
- [ ] Run salt highstate on `cove-360-live`
- [ ] Check that the correct commit has been deployed using the link in the footer http://dataquality.threesixtygiving.org/
- [ ] Run `CUSTOM_SERVER_URL=https://dataquality.threesixtygiving.org/ DJANGO_SETTINGS_MODULE=cove_360.settings py.test cove_360/tests_functional.py` on a local copy of the updated live branch
- [ ] Run salt highstate on `cove-live-ocds`
- [ ] Check that the correct commit has been deployed using the link in the footer http://standard.open-contracting.org/validator/
- [ ] Run `CUSTOM_SERVER_URL=http://standard.open-contracting.org/ DJANGO_SETTINGS_MODULE=cove_ocds.settings py.test cove_ocds/tests_functional.py` on a local copy of the updated live branch
- [ ] Check that changes on live are merged back into master too

### CODE REVIEW

**Comment by Bjwebb** [comment]
@stevieflow @BobHarper1 @KDuerden @morchickit - We're planning a release of the 360Giving data quality tool on Monday 22nd January. Summary of changes is at the top.

**Comment by Bjwebb** [comment]
@stevieflow @BobHarper1 @KDuerden @morchickit - We're planning a release of the 360Giving data quality tool on Monday 22nd January. Summary of changes and a link to test it are at the top of this pull request.

**Comment by Bjwebb** [comment]
@jpmckinney We're planning on updating the OCDS Validator on Monday, see the summary in the issue.

This should be the last monthly release for the OCDS Validator, as we have work on Continuous Deployment scheduled in the next sprint, in a couple of weeks time.

**Comment by KDuerden** [comment]
I've checked the changes and I'm happy they are working as intended. Ok to go from my perspective.

**Pull request merged**
