### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by BibianaC**
Bleach 3.1.3 to 3.1.4

### CODE REVIEW

**Comment by BibianaC** [comment]
@odscjames @Bjwebb I have ran:
`./update_requirements --new-only`

**Comment by odscjames** [comment]
I'm slightly puzzled; did you run ``./update_requirements --new-only`` and then update bleach by hand? Or did running  ``./update_requirements --new-only`` update bleach?

**Comment by odscjames** [comment]
(I checked https://github.com/mozilla/bleach/compare/v3.1.3...v3.1.4 and there are no changes to requirements there)

**Comment by BibianaC** [comment]
@odscjames ahhh so I might have done this in the wrong way. I have updated the version by hand and then ran `./update_requirements --new-only`. I suppose I only had to ran `./update_requirements --new-only`?

**Comment by BibianaC** [comment]
@odscjames I think now should be ok.

**Pull request merged**
